//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFlightInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myFlightInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _32_WebView2Loader {
            get {
                object obj = ResourceManager.GetObject("_32_WebView2Loader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _64_WebView2Loader {
            get {
                object obj = ResourceManager.GetObject("_64_WebView2Loader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;uk_airports&gt;
        ///	&lt;airport_info&gt;
        ///		&lt;icao_code&gt;CARK&lt;/icao_code&gt;
        ///		&lt;airport_name&gt;Cark airfield&lt;/airport_name&gt;
        ///		&lt;latitude_deg&gt;54°09&apos;45&quot;N&lt;/latitude_deg&gt;
        ///		&lt;latitude_dec&gt;54.1625&lt;/latitude_dec&gt;
        ///		&lt;longitude_deg&gt;2°57&apos;30&quot;W&lt;/longitude_deg&gt;
        ///		&lt;longitude_dec&gt;2.9583&lt;/longitude_dec&gt;
        ///		&lt;elevation_m&gt;5&lt;/elevation_m&gt;
        ///		&lt;elevation_ft&gt;16&lt;/elevation_ft&gt;
        ///		&lt;iata_code&gt;&lt;/iata_code&gt;
        ///		&lt;alternate_name&gt;&lt;/alternate_name&gt;
        ///		&lt;fir&gt;London FIR&lt;/fir&gt;
        ///		&lt;city&gt;Cark&lt;/city&gt;
        ///		&lt;type&gt;Small air [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string airport_data {
            get {
                return ResourceManager.GetString("airport_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] arm64_WebView2Loader {
            get {
                object obj = ResourceManager.GetObject("arm64_WebView2Loader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c42_sideview {
            get {
                object obj = ResourceManager.GetObject("c42_sideview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;compliance_data&gt;
        ///	&lt;aircraft_info&gt;
        ///		&lt;aircraft_name&gt;Default&lt;/aircraft_name&gt;
        ///		&lt;MaxTakeOffWeight&gt;450&lt;/MaxTakeOffWeight&gt;
        ///		&lt;EmptyWeight&gt;268&lt;/EmptyWeight&gt;
        ///		&lt;MinPilotWeight&gt;55&lt;/MinPilotWeight&gt;
        ///		&lt;MaxWeightPerCrewMember&gt;120&lt;/MaxWeightPerCrewMember&gt;
        ///		&lt;MaxCockpitWeight&gt;172&lt;/MaxCockpitWeight&gt;
        ///		&lt;MinCockpitWeight&gt;55&lt;/MinCockpitWeight&gt;
        ///		&lt;MaxWeightPerSeat&gt;120&lt;/MaxWeightPerSeat&gt;
        ///		&lt;MaxHoldBaggageWeight&gt;10&lt;/MaxHoldBaggageWeight&gt;
        ///		&lt;MaxFuelVol&gt;65&lt;/MaxFuelVol&gt;
        ///		&lt;Min [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string compliance_data {
            get {
                return ResourceManager.GetString("compliance_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CoordinateSharp {
            get {
                object obj = ResourceManager.GetObject("CoordinateSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CoordinateSharp_Magnetic {
            get {
                object obj = ResourceManager.GetObject("CoordinateSharp_Magnetic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Web_WebView2_Core {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Web_WebView2_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Web_WebView2_WinForms {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Web_WebView2_WinForms", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
